<?php
/**
 * Created by PhpStorm.
 * User: matias
 * Date: 2/5/16
 * Time: 12:33 PM
 */

namespace Matudelatower\UbicacionBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Matudelatower\UbicacionBundle\Entity\Departamento;


class LoadDepartamentoData extends AbstractFixture implements OrderedFixtureInterface {

	public function load( ObjectManager $manager ) {
		$departamentos = array(
			array( 'id' => 722, 'descripcion' => 'Anta', 'id_provincia' => '18' ),
			array( 'id' => 723, 'descripcion' => 'Cachi', 'id_provincia' => '18' ),
			array( 'id' => 724, 'descripcion' => 'Cafayate', 'id_provincia' => '18' ),
			array( 'id' => 725, 'descripcion' => 'Capital', 'id_provincia' => '18' ),
			array( 'id' => 726, 'descripcion' => 'Cerrillos', 'id_provincia' => '18' ),
			array( 'id' => 727, 'descripcion' => 'Chicoana', 'id_provincia' => '18' ),
			array( 'id' => 730, 'descripcion' => 'General Jose De San Martin', 'id_provincia' => '18' ),
			array( 'id' => 729, 'descripcion' => 'General Martin M Guemes', 'id_provincia' => '18' ),
			array( 'id' => 731, 'descripcion' => 'Guachipas', 'id_provincia' => '18' ),
			array( 'id' => 732, 'descripcion' => 'Iruya', 'id_provincia' => '18' ),
			array( 'id' => 733, 'descripcion' => 'La Caldera', 'id_provincia' => '18' ),
			array( 'id' => 921, 'descripcion' => 'La Candelaria', 'id_provincia' => '18' ),
			array( 'id' => 734, 'descripcion' => 'La Poma', 'id_provincia' => '18' ),
			array( 'id' => 736, 'descripcion' => 'Los Andes', 'id_provincia' => '18' ),
			array( 'id' => 737, 'descripcion' => 'Metan', 'id_provincia' => '18' ),
			array( 'id' => 738, 'descripcion' => 'Molinos', 'id_provincia' => '18' ),
			array( 'id' => 739, 'descripcion' => 'Oran', 'id_provincia' => '18' ),
			array( 'id' => 740, 'descripcion' => 'Rivadavia', 'id_provincia' => '18' ),
			array( 'id' => 741, 'descripcion' => 'Rosario De La Frontera', 'id_provincia' => '18' ),
			array( 'id' => 742, 'descripcion' => 'Rosario De Lerma', 'id_provincia' => '18' ),
			array( 'id' => 743, 'descripcion' => 'San Carlos', 'id_provincia' => '18' ),
			array( 'id' => 744, 'descripcion' => 'Santa Victoria', 'id_provincia' => '18' ),
			array( 'id' => 63, 'descripcion' => '25 De Mayo', 'id_provincia' => '2' ),
			array( 'id' => 64, 'descripcion' => '9 De Julio', 'id_provincia' => '2' ),
			array( 'id' => 65, 'descripcion' => 'Adolfo Alsina', 'id_provincia' => '2' ),
			array( 'id' => 66, 'descripcion' => 'Adolfo Gonzales Chaves', 'id_provincia' => '2' ),
			array( 'id' => 67, 'descripcion' => 'Alberti', 'id_provincia' => '2' ),
			array( 'id' => 955, 'descripcion' => 'Almirante Brown', 'id_provincia' => '2' ),
			array( 'id' => 72, 'descripcion' => 'Avellaneda', 'id_provincia' => '2' ),
			array( 'id' => 73, 'descripcion' => 'Ayacucho', 'id_provincia' => '2' ),
			array( 'id' => 74, 'descripcion' => 'Azul', 'id_provincia' => '2' ),
			array( 'id' => 75, 'descripcion' => 'Bahia Blanca', 'id_provincia' => '2' ),
			array( 'id' => 76, 'descripcion' => 'Balcarce', 'id_provincia' => '2' ),
			array( 'id' => 77, 'descripcion' => 'Baradero', 'id_provincia' => '2' ),
			array( 'id' => 78, 'descripcion' => 'Bartolome Mitre', 'id_provincia' => '2' ),
			array( 'id' => 80, 'descripcion' => 'Benito Juarez', 'id_provincia' => '2' ),
			array( 'id' => 950, 'descripcion' => 'Berazategui', 'id_provincia' => '2' ),
			array( 'id' => 82, 'descripcion' => 'Berisso', 'id_provincia' => '2' ),
			array( 'id' => 83, 'descripcion' => 'Bolivar', 'id_provincia' => '2' ),
			array( 'id' => 84, 'descripcion' => 'Bragado', 'id_provincia' => '2' ),
			array( 'id' => 86, 'descripcion' => 'Campana', 'id_provincia' => '2' ),
			array( 'id' => 88, 'descripcion' => 'Capitan Sarmiento', 'id_provincia' => '2' ),
			array( 'id' => 89, 'descripcion' => 'Carlos Casares', 'id_provincia' => '2' ),
			array( 'id' => 90, 'descripcion' => 'Carlos Tejedor', 'id_provincia' => '2' ),
			array( 'id' => 91, 'descripcion' => 'Carmen De Areco', 'id_provincia' => '2' ),
			array( 'id' => 94, 'descripcion' => 'Castelli', 'id_provincia' => '2' ),
			array( 'id' => 95, 'descripcion' => 'Chacabuco', 'id_provincia' => '2' ),
			array( 'id' => 96, 'descripcion' => 'Chascomus', 'id_provincia' => '2' ),
			array( 'id' => 97, 'descripcion' => 'Chivilcoy', 'id_provincia' => '2' ),
			array( 'id' => 98, 'descripcion' => 'Colon', 'id_provincia' => '2' ),
			array( 'id' => 85, 'descripcion' => 'Coronel Brandsen', 'id_provincia' => '2' ),
			array( 'id' => 100, 'descripcion' => 'Coronel Dorrego', 'id_provincia' => '2' ),
			array( 'id' => 101, 'descripcion' => 'Coronel Pringles', 'id_provincia' => '2' ),
			array( 'id' => 99, 'descripcion' => 'Coronel Rosales', 'id_provincia' => '2' ),
			array( 'id' => 102, 'descripcion' => 'Coronel Suarez', 'id_provincia' => '2' ),
			array( 'id' => 103, 'descripcion' => 'Daireaux', 'id_provincia' => '2' ),
			array( 'id' => 411, 'descripcion' => 'De La Costa', 'id_provincia' => '2' ),
			array( 'id' => 104, 'descripcion' => 'Dolores', 'id_provincia' => '2' ),
			array( 'id' => 105, 'descripcion' => 'Ensenada', 'id_provincia' => '2' ),
			array( 'id' => 106, 'descripcion' => 'Escobar', 'id_provincia' => '2' ),
			array( 'id' => 407, 'descripcion' => 'Esteban Echeverria', 'id_provincia' => '2' ),
			array( 'id' => 108, 'descripcion' => 'Exaltacion De La Cruz', 'id_provincia' => '2' ),
			array( 'id' => 929, 'descripcion' => 'Ezeiza', 'id_provincia' => '2' ),
			array( 'id' => 949, 'descripcion' => 'Florencio Varela', 'id_provincia' => '2' ),
			array( 'id' => 71, 'descripcion' => 'Florentino Ameghino', 'id_provincia' => '2' ),
			array( 'id' => 69, 'descripcion' => 'General Alvarado', 'id_provincia' => '2' ),
			array( 'id' => 70, 'descripcion' => 'General Alvear', 'id_provincia' => '2' ),
			array( 'id' => 111, 'descripcion' => 'General Arenales', 'id_provincia' => '2' ),
			array( 'id' => 112, 'descripcion' => 'General Belgrano', 'id_provincia' => '2' ),
			array( 'id' => 113, 'descripcion' => 'General Guido', 'id_provincia' => '2' ),
			array( 'id' => 129, 'descripcion' => 'General Lamadrid', 'id_provincia' => '2' ),
			array( 'id' => 133, 'descripcion' => 'General Las Heras', 'id_provincia' => '2' ),
			array( 'id' => 114, 'descripcion' => 'General Lavalle', 'id_provincia' => '2' ),
			array( 'id' => 115, 'descripcion' => 'General Madariaga', 'id_provincia' => '2' ),
			array( 'id' => 116, 'descripcion' => 'General Paz', 'id_provincia' => '2' ),
			array( 'id' => 117, 'descripcion' => 'General Pinto', 'id_provincia' => '2' ),
			array( 'id' => 162, 'descripcion' => 'General Pueyrredon', 'id_provincia' => '2' ),
			array( 'id' => 954, 'descripcion' => 'General Rodriguez', 'id_provincia' => '2' ),
			array( 'id' => 947, 'descripcion' => 'General San Martin', 'id_provincia' => '2' ),
			array( 'id' => 193, 'descripcion' => 'General Viamonte', 'id_provincia' => '2' ),
			array( 'id' => 120, 'descripcion' => 'General Villegas', 'id_provincia' => '2' ),
			array( 'id' => 121, 'descripcion' => 'Guamini', 'id_provincia' => '2' ),
			array( 'id' => 196, 'descripcion' => 'Hipolito Yrigoyen', 'id_provincia' => '2' ),
			array( 'id' => 923, 'descripcion' => 'Hurlingham', 'id_provincia' => '2' ),
			array( 'id' => 926, 'descripcion' => 'Ituzaingo', 'id_provincia' => '2' ),
			array( 'id' => 934, 'descripcion' => 'Jose Clemente Paz', 'id_provincia' => '2' ),
			array( 'id' => 126, 'descripcion' => 'Junin', 'id_provincia' => '2' ),
			array( 'id' => 933, 'descripcion' => 'La Matanza', 'id_provincia' => '2' ),
			array( 'id' => 128, 'descripcion' => 'La Plata', 'id_provincia' => '2' ),
			array( 'id' => 130, 'descripcion' => 'Lanus', 'id_provincia' => '2' ),
			array( 'id' => 131, 'descripcion' => 'Laprida', 'id_provincia' => '2' ),
			array( 'id' => 132, 'descripcion' => 'Las Flores', 'id_provincia' => '2' ),
			array( 'id' => 134, 'descripcion' => 'Leandro N Alem', 'id_provincia' => '2' ),
			array( 'id' => 135, 'descripcion' => 'Lincoln', 'id_provincia' => '2' ),
			array( 'id' => 136, 'descripcion' => 'Loberia', 'id_provincia' => '2' ),
			array( 'id' => 137, 'descripcion' => 'Lobos', 'id_provincia' => '2' ),
			array( 'id' => 927, 'descripcion' => 'Lomas De Zamora', 'id_provincia' => '2' ),
			array( 'id' => 139, 'descripcion' => 'Lujan', 'id_provincia' => '2' ),
			array( 'id' => 140, 'descripcion' => 'Magdalena', 'id_provincia' => '2' ),
			array( 'id' => 141, 'descripcion' => 'Maipu', 'id_provincia' => '2' ),
			array( 'id' => 930, 'descripcion' => 'Malvinas Argentinas', 'id_provincia' => '2' ),
			array( 'id' => 143, 'descripcion' => 'Mar Chiquita', 'id_provincia' => '2' ),
			array( 'id' => 144, 'descripcion' => 'Marcos Paz', 'id_provincia' => '2' ),
			array( 'id' => 145, 'descripcion' => 'Mercedes', 'id_provincia' => '2' ),
			array( 'id' => 948, 'descripcion' => 'Merlo', 'id_provincia' => '2' ),
			array( 'id' => 180, 'descripcion' => 'Monte', 'id_provincia' => '2' ),
			array( 'id' => 147, 'descripcion' => 'Monte Hermoso', 'id_provincia' => '2' ),
			array( 'id' => 939, 'descripcion' => 'Moreno', 'id_provincia' => '2' ),
			array( 'id' => 924, 'descripcion' => 'Moron', 'id_provincia' => '2' ),
			array( 'id' => 150, 'descripcion' => 'Navarro', 'id_provincia' => '2' ),
			array( 'id' => 151, 'descripcion' => 'Necochea', 'id_provincia' => '2' ),
			array( 'id' => 154, 'descripcion' => 'Olavarria', 'id_provincia' => '2' ),
			array( 'id' => 92, 'descripcion' => 'Patagones', 'id_provincia' => '2' ),
			array( 'id' => 155, 'descripcion' => 'Pehuajo', 'id_provincia' => '2' ),
			array( 'id' => 156, 'descripcion' => 'Pellegrini', 'id_provincia' => '2' ),
			array( 'id' => 157, 'descripcion' => 'Pergamino', 'id_provincia' => '2' ),
			array( 'id' => 158, 'descripcion' => 'Pila', 'id_provincia' => '2' ),
			array( 'id' => 159, 'descripcion' => 'Pilar', 'id_provincia' => '2' ),
			array( 'id' => 410, 'descripcion' => 'Pinamar', 'id_provincia' => '2' ),
			array( 'id' => 953, 'descripcion' => 'Presidente Peron', 'id_provincia' => '2' ),
			array( 'id' => 161, 'descripcion' => 'Puan', 'id_provincia' => '2' ),
			array( 'id' => 409, 'descripcion' => 'Punta Indio', 'id_provincia' => '2' ),
			array( 'id' => 943, 'descripcion' => 'Quilmes', 'id_provincia' => '2' ),
			array( 'id' => 164, 'descripcion' => 'Ramallo', 'id_provincia' => '2' ),
			array( 'id' => 165, 'descripcion' => 'Rauch', 'id_provincia' => '2' ),
			array( 'id' => 166, 'descripcion' => 'Rivadavia', 'id_provincia' => '2' ),
			array( 'id' => 167, 'descripcion' => 'Rojas', 'id_provincia' => '2' ),
			array( 'id' => 168, 'descripcion' => 'Roque Perez', 'id_provincia' => '2' ),
			array( 'id' => 169, 'descripcion' => 'Saavedra', 'id_provincia' => '2' ),
			array( 'id' => 170, 'descripcion' => 'Saladillo', 'id_provincia' => '2' ),
			array( 'id' => 171, 'descripcion' => 'Salliquelo', 'id_provincia' => '2' ),
			array( 'id' => 172, 'descripcion' => 'Salto', 'id_provincia' => '2' ),
			array( 'id' => 173, 'descripcion' => 'San Andres De Giles', 'id_provincia' => '2' ),
			array( 'id' => 174, 'descripcion' => 'San Antonio De Areco', 'id_provincia' => '2' ),
			array( 'id' => 175, 'descripcion' => 'San Cayetano', 'id_provincia' => '2' ),
			array( 'id' => 925, 'descripcion' => 'San Fernando', 'id_provincia' => '2' ),
			array( 'id' => 177, 'descripcion' => 'San Isidro', 'id_provincia' => '2' ),
			array( 'id' => 938, 'descripcion' => 'San Miguel', 'id_provincia' => '2' ),
			array( 'id' => 951, 'descripcion' => 'San Nicolas', 'id_provincia' => '2' ),
			array( 'id' => 182, 'descripcion' => 'San Pedro', 'id_provincia' => '2' ),
			array( 'id' => 183, 'descripcion' => 'San Vicente', 'id_provincia' => '2' ),
			array( 'id' => 184, 'descripcion' => 'Suipacha', 'id_provincia' => '2' ),
			array( 'id' => 185, 'descripcion' => 'Tandil', 'id_provincia' => '2' ),
			array( 'id' => 186, 'descripcion' => 'Tapalque', 'id_provincia' => '2' ),
			array( 'id' => 940, 'descripcion' => 'Tigre', 'id_provincia' => '2' ),
			array( 'id' => 188, 'descripcion' => 'Tordillo', 'id_provincia' => '2' ),
			array( 'id' => 189, 'descripcion' => 'Tornquist', 'id_provincia' => '2' ),
			array( 'id' => 190, 'descripcion' => 'Trenque Lauquen', 'id_provincia' => '2' ),
			array( 'id' => 191, 'descripcion' => 'Tres Arroyos', 'id_provincia' => '2' ),
			array( 'id' => 932, 'descripcion' => 'Tres De Febrero', 'id_provincia' => '2' ),
			array( 'id' => 922, 'descripcion' => 'Tres Lomas', 'id_provincia' => '2' ),
			array( 'id' => 952, 'descripcion' => 'Vicente Lopez', 'id_provincia' => '2' ),
			array( 'id' => 412, 'descripcion' => 'Villa Gesell', 'id_provincia' => '2' ),
			array( 'id' => 195, 'descripcion' => 'Villarino', 'id_provincia' => '2' ),
			array( 'id' => 197, 'descripcion' => 'Zarate', 'id_provincia' => '2' ),
			array( 'id' => 198, 'descripcion' => 'Capital Federal', 'id_provincia' => '3' ),
			array( 'id' => 863, 'descripcion' => 'Ayacucho', 'id_provincia' => '20' ),
			array( 'id' => 864, 'descripcion' => 'Belgrano', 'id_provincia' => '20' ),
			array( 'id' => 865, 'descripcion' => 'Chacabuco', 'id_provincia' => '20' ),
			array( 'id' => 866, 'descripcion' => 'Coronel Pringles', 'id_provincia' => '20' ),
			array( 'id' => 868, 'descripcion' => 'General Pedernera', 'id_provincia' => '20' ),
			array( 'id' => 867, 'descripcion' => 'Gobernador Dupuy', 'id_provincia' => '20' ),
			array( 'id' => 869, 'descripcion' => 'Junin', 'id_provincia' => '20' ),
			array( 'id' => 870, 'descripcion' => 'La Capital', 'id_provincia' => '20' ),
			array( 'id' => 871, 'descripcion' => 'Libertador Gral San Martin', 'id_provincia' => '20' ),
			array( 'id' => 593, 'descripcion' => 'Colon', 'id_provincia' => '9' ),
			array( 'id' => 594, 'descripcion' => 'Concordia', 'id_provincia' => '9' ),
			array( 'id' => 595, 'descripcion' => 'Diamante', 'id_provincia' => '9' ),
			array( 'id' => 596, 'descripcion' => 'Federacion', 'id_provincia' => '9' ),
			array( 'id' => 597, 'descripcion' => 'Federal', 'id_provincia' => '9' ),
			array( 'id' => 598, 'descripcion' => 'Feliciano', 'id_provincia' => '9' ),
			array( 'id' => 599, 'descripcion' => 'Gualeguay', 'id_provincia' => '9' ),
			array( 'id' => 600, 'descripcion' => 'Gualeguaychu', 'id_provincia' => '9' ),
			array( 'id' => 601, 'descripcion' => 'Islas Del Ibicuy', 'id_provincia' => '9' ),
			array( 'id' => 602, 'descripcion' => 'La Paz', 'id_provincia' => '9' ),
			array( 'id' => 603, 'descripcion' => 'Nogoya', 'id_provincia' => '9' ),
			array( 'id' => 604, 'descripcion' => 'Parana', 'id_provincia' => '9' ),
			array( 'id' => 606, 'descripcion' => 'Tala', 'id_provincia' => '9' ),
			array( 'id' => 607, 'descripcion' => 'Uruguay', 'id_provincia' => '9' ),
			array( 'id' => 608, 'descripcion' => 'Victoria', 'id_provincia' => '9' ),
			array( 'id' => 609, 'descripcion' => 'Villaguay', 'id_provincia' => '9' ),
			array( 'id' => 811, 'descripcion' => 'Arauco', 'id_provincia' => '13' ),
			array( 'id' => 813, 'descripcion' => 'Capital', 'id_provincia' => '13' ),
			array( 'id' => 814, 'descripcion' => 'Castro Barros', 'id_provincia' => '13' ),
			array( 'id' => 815, 'descripcion' => 'Chamical', 'id_provincia' => '13' ),
			array( 'id' => 816, 'descripcion' => 'Chilecito', 'id_provincia' => '13' ),
			array( 'id' => 817, 'descripcion' => 'Coronel Felipe Varela', 'id_provincia' => '13' ),
			array( 'id' => 819, 'descripcion' => 'Famatina', 'id_provincia' => '13' ),
			array( 'id' => 822, 'descripcion' => 'General Belgrano', 'id_provincia' => '13' ),
			array( 'id' => 824, 'descripcion' => 'General Juan Facundo Quiroga', 'id_provincia' => '13' ),
			array( 'id' => 825, 'descripcion' => 'General Lamadrid', 'id_provincia' => '13' ),
			array( 'id' => 826, 'descripcion' => 'General Ocampo', 'id_provincia' => '13' ),
			array( 'id' => 827, 'descripcion' => 'General San Martin', 'id_provincia' => '13' ),
			array( 'id' => 832, 'descripcion' => 'General Sarmiento', 'id_provincia' => '13' ),
			array( 'id' => 820, 'descripcion' => 'Gobernador Gordillo', 'id_provincia' => '13' ),
			array( 'id' => 828, 'descripcion' => 'Independencia', 'id_provincia' => '13' ),
			array( 'id' => 830, 'descripcion' => 'San Blas De Los Sauces', 'id_provincia' => '13' ),
			array( 'id' => 831, 'descripcion' => 'Sanagasta', 'id_provincia' => '13' ),
			array( 'id' => 833, 'descripcion' => 'Vinchina', 'id_provincia' => '13' ),
			array( 'id' => 834, 'descripcion' => 'Aguirre', 'id_provincia' => '23' ),
			array( 'id' => 835, 'descripcion' => 'Alberdi', 'id_provincia' => '23' ),
			array( 'id' => 836, 'descripcion' => 'Atamisqui', 'id_provincia' => '23' ),
			array( 'id' => 837, 'descripcion' => 'Avellaneda', 'id_provincia' => '23' ),
			array( 'id' => 838, 'descripcion' => 'Banda', 'id_provincia' => '23' ),
			array( 'id' => 839, 'descripcion' => 'Belgrano', 'id_provincia' => '23' ),
			array( 'id' => 849, 'descripcion' => 'Brigadier Juan F Ibarra', 'id_provincia' => '23' ),
			array( 'id' => 840, 'descripcion' => 'Capital', 'id_provincia' => '23' ),
			array( 'id' => 841, 'descripcion' => 'Choya', 'id_provincia' => '23' ),
			array( 'id' => 842, 'descripcion' => 'Copo', 'id_provincia' => '23' ),
			array( 'id' => 843, 'descripcion' => 'Figueroa', 'id_provincia' => '23' ),
			array( 'id' => 859, 'descripcion' => 'General San Martin', 'id_provincia' => '23' ),
			array( 'id' => 844, 'descripcion' => 'General Taboada', 'id_provincia' => '23' ),
			array( 'id' => 847, 'descripcion' => 'Guasayan', 'id_provincia' => '23' ),
			array( 'id' => 848, 'descripcion' => 'Jimenez', 'id_provincia' => '23' ),
			array( 'id' => 850, 'descripcion' => 'Loreto', 'id_provincia' => '23' ),
			array( 'id' => 920, 'descripcion' => 'Mitre', 'id_provincia' => '23' ),
			array( 'id' => 851, 'descripcion' => 'Moreno', 'id_provincia' => '23' ),
			array( 'id' => 852, 'descripcion' => 'Ojo De Agua', 'id_provincia' => '23' ),
			array( 'id' => 853, 'descripcion' => 'Pellegrini', 'id_provincia' => '23' ),
			array( 'id' => 854, 'descripcion' => 'Quebrachos', 'id_provincia' => '23' ),
			array( 'id' => 855, 'descripcion' => 'Rio Hondo', 'id_provincia' => '23' ),
			array( 'id' => 856, 'descripcion' => 'Rivadavia', 'id_provincia' => '23' ),
			array( 'id' => 857, 'descripcion' => 'Robles', 'id_provincia' => '23' ),
			array( 'id' => 858, 'descripcion' => 'Salavina', 'id_provincia' => '23' ),
			array( 'id' => 860, 'descripcion' => 'Sarmiento', 'id_provincia' => '23' ),
			array( 'id' => 861, 'descripcion' => 'Silipica', 'id_provincia' => '23' ),
			array( 'id' => 680, 'descripcion' => '1 De Mayo', 'id_provincia' => '5' ),
			array( 'id' => 682, 'descripcion' => '12 De Octubre', 'id_provincia' => '5' ),
			array( 'id' => 684, 'descripcion' => '25 De Mayo', 'id_provincia' => '5' ),
			array( 'id' => 686, 'descripcion' => '9 De Julio', 'id_provincia' => '5' ),
			array( 'id' => 688, 'descripcion' => 'Almirante Brown', 'id_provincia' => '5' ),
			array( 'id' => 689, 'descripcion' => 'Bermejo', 'id_provincia' => '5' ),
			array( 'id' => 691, 'descripcion' => 'Chacabuco', 'id_provincia' => '5' ),
			array( 'id' => 693, 'descripcion' => 'Comandante Fernandez', 'id_provincia' => '5' ),
			array( 'id' => 695, 'descripcion' => 'Fray Justo Santa Maria De Oro', 'id_provincia' => '5' ),
			array( 'id' => 697, 'descripcion' => 'General Belgrano', 'id_provincia' => '5' ),
			array( 'id' => 698, 'descripcion' => 'General Donovan', 'id_provincia' => '5' ),
			array( 'id' => 700, 'descripcion' => 'General Guemes', 'id_provincia' => '5' ),
			array( 'id' => 702, 'descripcion' => 'Independencia', 'id_provincia' => '5' ),
			array( 'id' => 705, 'descripcion' => 'Libertad', 'id_provincia' => '5' ),
			array( 'id' => 703, 'descripcion' => 'Libertador Gral San Martin', 'id_provincia' => '5' ),
			array( 'id' => 707, 'descripcion' => 'Maipu', 'id_provincia' => '5' ),
			array( 'id' => 709, 'descripcion' => 'Mayor Luis J Fontana', 'id_provincia' => '5' ),
			array( 'id' => 710, 'descripcion' => 'O Higgins', 'id_provincia' => '5' ),
			array( 'id' => 712, 'descripcion' => 'Presidente De La Plaza', 'id_provincia' => '5' ),
			array( 'id' => 714, 'descripcion' => 'Quitilipi', 'id_provincia' => '5' ),
			array( 'id' => 715, 'descripcion' => 'San Fernando', 'id_provincia' => '5' ),
			array( 'id' => 717, 'descripcion' => 'San Lorenzo', 'id_provincia' => '5' ),
			array( 'id' => 718, 'descripcion' => 'Sargento Cabral', 'id_provincia' => '5' ),
			array( 'id' => 720, 'descripcion' => 'Tapenaga', 'id_provincia' => '5' ),
			array( 'id' => 875, 'descripcion' => '25 De Mayo', 'id_provincia' => '19' ),
			array( 'id' => 876, 'descripcion' => '9 De Julio', 'id_provincia' => '19' ),
			array( 'id' => 877, 'descripcion' => 'Albardon', 'id_provincia' => '19' ),
			array( 'id' => 878, 'descripcion' => 'Angaco', 'id_provincia' => '19' ),
			array( 'id' => 879, 'descripcion' => 'Calingasta', 'id_provincia' => '19' ),
			array( 'id' => 880, 'descripcion' => 'Capital', 'id_provincia' => '19' ),
			array( 'id' => 881, 'descripcion' => 'Caucete', 'id_provincia' => '19' ),
			array( 'id' => 882, 'descripcion' => 'Chimbas', 'id_provincia' => '19' ),
			array( 'id' => 883, 'descripcion' => 'Iglesia', 'id_provincia' => '19' ),
			array( 'id' => 884, 'descripcion' => 'Jachal', 'id_provincia' => '19' ),
			array( 'id' => 885, 'descripcion' => 'Pocito', 'id_provincia' => '19' ),
			array( 'id' => 886, 'descripcion' => 'Rawson', 'id_provincia' => '19' ),
			array( 'id' => 887, 'descripcion' => 'Rivadavia', 'id_provincia' => '19' ),
			array( 'id' => 888, 'descripcion' => 'San Martin', 'id_provincia' => '19' ),
			array( 'id' => 889, 'descripcion' => 'Santa Lucia', 'id_provincia' => '19' ),
			array( 'id' => 890, 'descripcion' => 'Sarmiento', 'id_provincia' => '19' ),
			array( 'id' => 891, 'descripcion' => 'Ullum', 'id_provincia' => '19' ),
			array( 'id' => 892, 'descripcion' => 'Valle Fertil', 'id_provincia' => '19' ),
			array( 'id' => 919, 'descripcion' => 'Zonda', 'id_provincia' => '19' ),
			array( 'id' => 657, 'descripcion' => 'Ambato', 'id_provincia' => '4' ),
			array( 'id' => 658, 'descripcion' => 'Ancasti', 'id_provincia' => '4' ),
			array( 'id' => 659, 'descripcion' => 'Andalgala', 'id_provincia' => '4' ),
			array( 'id' => 661, 'descripcion' => 'Antofagasta De La Sierra', 'id_provincia' => '4' ),
			array( 'id' => 662, 'descripcion' => 'Belen', 'id_provincia' => '4' ),
			array( 'id' => 663, 'descripcion' => 'Capayan', 'id_provincia' => '4' ),
			array( 'id' => 664, 'descripcion' => 'Capital', 'id_provincia' => '4' ),
			array( 'id' => 666, 'descripcion' => 'El Alto', 'id_provincia' => '4' ),
			array( 'id' => 669, 'descripcion' => 'Fray Mamerto Esquiu', 'id_provincia' => '4' ),
			array( 'id' => 670, 'descripcion' => 'La Paz', 'id_provincia' => '4' ),
			array( 'id' => 673, 'descripcion' => 'Paclin', 'id_provincia' => '4' ),
			array( 'id' => 674, 'descripcion' => 'Poman', 'id_provincia' => '4' ),
			array( 'id' => 675, 'descripcion' => 'Santa Maria', 'id_provincia' => '4' ),
			array( 'id' => 676, 'descripcion' => 'Santa Rosa', 'id_provincia' => '4' ),
			array( 'id' => 678, 'descripcion' => 'Tinogasta', 'id_provincia' => '4' ),
			array( 'id' => 679, 'descripcion' => 'Valle Viejo', 'id_provincia' => '4' ),
			array( 'id' => 512, 'descripcion' => 'Atreuco', 'id_provincia' => '12' ),
			array( 'id' => 513, 'descripcion' => 'Caleu Caleu', 'id_provincia' => '12' ),
			array( 'id' => 514, 'descripcion' => 'Capital', 'id_provincia' => '12' ),
			array( 'id' => 515, 'descripcion' => 'Catrilo', 'id_provincia' => '12' ),
			array( 'id' => 516, 'descripcion' => 'Chalileo', 'id_provincia' => '12' ),
			array( 'id' => 517, 'descripcion' => 'Chapaleufu', 'id_provincia' => '12' ),
			array( 'id' => 518, 'descripcion' => 'Chical Co', 'id_provincia' => '12' ),
			array( 'id' => 520, 'descripcion' => 'Conhelo', 'id_provincia' => '12' ),
			array( 'id' => 521, 'descripcion' => 'Curaco', 'id_provincia' => '12' ),
			array( 'id' => 522, 'descripcion' => 'Guatrache', 'id_provincia' => '12' ),
			array( 'id' => 523, 'descripcion' => 'Hucal', 'id_provincia' => '12' ),
			array( 'id' => 524, 'descripcion' => 'Lihuel Calel', 'id_provincia' => '12' ),
			array( 'id' => 526, 'descripcion' => 'Limay Mahuida', 'id_provincia' => '12' ),
			array( 'id' => 527, 'descripcion' => 'Loventue', 'id_provincia' => '12' ),
			array( 'id' => 528, 'descripcion' => 'Maraco', 'id_provincia' => '12' ),
			array( 'id' => 529, 'descripcion' => 'Puelen', 'id_provincia' => '12' ),
			array( 'id' => 530, 'descripcion' => 'Quemu Quemu', 'id_provincia' => '12' ),
			array( 'id' => 531, 'descripcion' => 'Rancul', 'id_provincia' => '12' ),
			array( 'id' => 532, 'descripcion' => 'Realico', 'id_provincia' => '12' ),
			array( 'id' => 533, 'descripcion' => 'Toay', 'id_provincia' => '12' ),
			array( 'id' => 534, 'descripcion' => 'Trenel', 'id_provincia' => '12' ),
			array( 'id' => 535, 'descripcion' => 'Utracan', 'id_provincia' => '12' ),
			array( 'id' => 426, 'descripcion' => 'Capital', 'id_provincia' => '14' ),
			array( 'id' => 428, 'descripcion' => 'General Alvear', 'id_provincia' => '14' ),
			array( 'id' => 427, 'descripcion' => 'Godoy Cruz', 'id_provincia' => '14' ),
			array( 'id' => 433, 'descripcion' => 'Guaymallen', 'id_provincia' => '14' ),
			array( 'id' => 435, 'descripcion' => 'Junin', 'id_provincia' => '14' ),
			array( 'id' => 436, 'descripcion' => 'La Paz', 'id_provincia' => '14' ),
			array( 'id' => 438, 'descripcion' => 'Las Heras', 'id_provincia' => '14' ),
			array( 'id' => 439, 'descripcion' => 'Lavalle', 'id_provincia' => '14' ),
			array( 'id' => 443, 'descripcion' => 'Lujan De Cuyo', 'id_provincia' => '14' ),
			array( 'id' => 444, 'descripcion' => 'Maipu', 'id_provincia' => '14' ),
			array( 'id' => 445, 'descripcion' => 'Malargue', 'id_provincia' => '14' ),
			array( 'id' => 446, 'descripcion' => 'Rivadavia', 'id_provincia' => '14' ),
			array( 'id' => 447, 'descripcion' => 'San Carlos', 'id_provincia' => '14' ),
			array( 'id' => 448, 'descripcion' => 'San Martin', 'id_provincia' => '14' ),
			array( 'id' => 449, 'descripcion' => 'San Rafael', 'id_provincia' => '14' ),
			array( 'id' => 450, 'descripcion' => 'Santa Rosa', 'id_provincia' => '14' ),
			array( 'id' => 451, 'descripcion' => 'Tunuyan', 'id_provincia' => '14' ),
			array( 'id' => 452, 'descripcion' => 'Tupungato', 'id_provincia' => '14' ),
			array( 'id' => 611, 'descripcion' => '25 De Mayo', 'id_provincia' => '15' , 'codigo_departamento'=> '17' ),
			array( 'id' => 612, 'descripcion' => 'Apóstoles', 'id_provincia' => '15' , 'codigo_departamento'=> '1' ),
			array( 'id' => 613, 'descripcion' => 'Cainguás', 'id_provincia' => '15' , 'codigo_departamento'=> '2' ),
			array( 'id' => 614, 'descripcion' => 'Candelaria', 'id_provincia' => '15' , 'codigo_departamento'=> '3' ),
			array( 'id' => 615, 'descripcion' => 'Capital', 'id_provincia' => '15' , 'codigo_departamento'=> '4' ),
			array( 'id' => 616, 'descripcion' => 'Concepción', 'id_provincia' => '15' , 'codigo_departamento'=> '5' ),
			array( 'id' => 618, 'descripcion' => 'Eldorado', 'id_provincia' => '15' , 'codigo_departamento'=> '6' ),
			array( 'id' => 619, 'descripcion' => 'General Manuel Belgrano', 'id_provincia' => '15' , 'codigo_departamento'=> '7' ),
			array( 'id' => 620, 'descripcion' => 'Guaraní', 'id_provincia' => '15' , 'codigo_departamento'=> '8' ),
			array( 'id' => 621, 'descripcion' => 'Iguazú', 'id_provincia' => '15' , 'codigo_departamento'=> '9' ),
			array( 'id' => 622, 'descripcion' => 'Leandro N Alem', 'id_provincia' => '15' , 'codigo_departamento'=> '10' ),
			array( 'id' => 623, 'descripcion' => 'Libertador Gral San Martin', 'id_provincia' => '15' , 'codigo_departamento'=> '11' ),
			array( 'id' => 625, 'descripcion' => 'Montecarlo', 'id_provincia' => '15' , 'codigo_departamento'=> '12' ),
			array( 'id' => 627, 'descripcion' => 'Oberá', 'id_provincia' => '15' , 'codigo_departamento'=> '13' ),
			array( 'id' => 628, 'descripcion' => 'San Ignacio', 'id_provincia' => '15' , 'codigo_departamento'=> '14' ),
			array( 'id' => 629, 'descripcion' => 'San Javier', 'id_provincia' => '15' , 'codigo_departamento'=> '15' ),
			array( 'id' => 630, 'descripcion' => 'San Pedro', 'id_provincia' => '15' , 'codigo_departamento'=> '16' ),
			array( 'id' => 582, 'descripcion' => 'Bermejo', 'id_provincia' => '10' ),
			array( 'id' => 583, 'descripcion' => 'Formosa', 'id_provincia' => '10' ),
			array( 'id' => 585, 'descripcion' => 'Laishi', 'id_provincia' => '10' ),
			array( 'id' => 586, 'descripcion' => 'Matacos', 'id_provincia' => '10' ),
			array( 'id' => 588, 'descripcion' => 'Pilagas', 'id_provincia' => '10' ),
			array( 'id' => 589, 'descripcion' => 'Pilcomayo', 'id_provincia' => '10' ),
			array( 'id' => 590, 'descripcion' => 'Pirane', 'id_provincia' => '10' ),
			array( 'id' => 591, 'descripcion' => 'Ramon Lista', 'id_provincia' => '10' ),
			array( 'id' => 552, 'descripcion' => 'Alumine', 'id_provincia' => '16' ),
			array( 'id' => 554, 'descripcion' => 'Catan Lil', 'id_provincia' => '16' ),
			array( 'id' => 556, 'descripcion' => 'Chos Malal', 'id_provincia' => '16' ),
			array( 'id' => 557, 'descripcion' => 'Collon Cura', 'id_provincia' => '16' ),
			array( 'id' => 558, 'descripcion' => 'Confluencia', 'id_provincia' => '16' ),
			array( 'id' => 559, 'descripcion' => 'Huiliches', 'id_provincia' => '16' ),
			array( 'id' => 561, 'descripcion' => 'Lacar', 'id_provincia' => '16' ),
			array( 'id' => 562, 'descripcion' => 'Loncopue', 'id_provincia' => '16' ),
			array( 'id' => 563, 'descripcion' => 'Los Lagos', 'id_provincia' => '16' ),
			array( 'id' => 564, 'descripcion' => 'Minas', 'id_provincia' => '16' ),
			array( 'id' => 566, 'descripcion' => 'Pehuenches', 'id_provincia' => '16' ),
			array( 'id' => 567, 'descripcion' => 'Picun Leufu', 'id_provincia' => '16' ),
			array( 'id' => 568, 'descripcion' => 'Picunches', 'id_provincia' => '16' ),
			array( 'id' => 569, 'descripcion' => 'Zapala', 'id_provincia' => '16' ),
			array( 'id' => 413, 'descripcion' => '25 De Mayo', 'id_provincia' => '17' ),
			array( 'id' => 414, 'descripcion' => '9 De Julio', 'id_provincia' => '17' ),
			array( 'id' => 415, 'descripcion' => 'Adolfo Alsina', 'id_provincia' => '17' ),
			array( 'id' => 416, 'descripcion' => 'Avellaneda', 'id_provincia' => '17' ),
			array( 'id' => 417, 'descripcion' => 'Bariloche', 'id_provincia' => '17' ),
			array( 'id' => 418, 'descripcion' => 'Conesa', 'id_provincia' => '17' ),
			array( 'id' => 419, 'descripcion' => 'El Cuy', 'id_provincia' => '17' ),
			array( 'id' => 420, 'descripcion' => 'General Roca', 'id_provincia' => '17' ),
			array( 'id' => 422, 'descripcion' => 'Pichi Mahuida', 'id_provincia' => '17' ),
			array( 'id' => 423, 'descripcion' => 'Pilcaniyeu', 'id_provincia' => '17' ),
			array( 'id' => 424, 'descripcion' => 'San Antonio', 'id_provincia' => '17' ),
			array( 'id' => 425, 'descripcion' => 'Valcheta', 'id_provincia' => '17' ),
			array( 'id' => 28, 'descripcion' => '9 De Julio', 'id_provincia' => '22' ),
			array( 'id' => 30, 'descripcion' => 'Belgrano', 'id_provincia' => '22' ),
			array( 'id' => 31, 'descripcion' => 'Caseros', 'id_provincia' => '22' ),
			array( 'id' => 32, 'descripcion' => 'Castellanos', 'id_provincia' => '22' ),
			array( 'id' => 34, 'descripcion' => 'Constitucion', 'id_provincia' => '22' ),
			array( 'id' => 37, 'descripcion' => 'Garay', 'id_provincia' => '22' ),
			array( 'id' => 44, 'descripcion' => 'General Lopez', 'id_provincia' => '22' ),
			array( 'id' => 45, 'descripcion' => 'General Obligado', 'id_provincia' => '22' ),
			array( 'id' => 38, 'descripcion' => 'Iriondo', 'id_provincia' => '22' ),
			array( 'id' => 42, 'descripcion' => 'La Capital', 'id_provincia' => '22' ),
			array( 'id' => 43, 'descripcion' => 'Las Colonias', 'id_provincia' => '22' ),
			array( 'id' => 46, 'descripcion' => 'Rosario', 'id_provincia' => '22' ),
			array( 'id' => 47, 'descripcion' => 'San Cristobal', 'id_provincia' => '22' ),
			array( 'id' => 48, 'descripcion' => 'San Javier', 'id_provincia' => '22' ),
			array( 'id' => 49, 'descripcion' => 'San Jeronimo', 'id_provincia' => '22' ),
			array( 'id' => 50, 'descripcion' => 'San Justo', 'id_provincia' => '22' ),
			array( 'id' => 51, 'descripcion' => 'San Lorenzo', 'id_provincia' => '22' ),
			array( 'id' => 52, 'descripcion' => 'San Martin', 'id_provincia' => '22' ),
			array( 'id' => 53, 'descripcion' => 'Vera', 'id_provincia' => '22' ),
			array( 'id' => 745, 'descripcion' => 'Burruyacu', 'id_provincia' => '25' ),
			array( 'id' => 746, 'descripcion' => 'Capital', 'id_provincia' => '25' ),
			array( 'id' => 747, 'descripcion' => 'Chicligasta', 'id_provincia' => '25' ),
			array( 'id' => 748, 'descripcion' => 'Cruz Alta', 'id_provincia' => '25' ),
			array( 'id' => 750, 'descripcion' => 'Famailla', 'id_provincia' => '25' ),
			array( 'id' => 751, 'descripcion' => 'Graneros', 'id_provincia' => '25' ),
			array( 'id' => 753, 'descripcion' => 'Juan B Alberdi', 'id_provincia' => '25' ),
			array( 'id' => 754, 'descripcion' => 'La Cocha', 'id_provincia' => '25' ),
			array( 'id' => 755, 'descripcion' => 'Leales', 'id_provincia' => '25' ),
			array( 'id' => 756, 'descripcion' => 'Lules', 'id_provincia' => '25' ),
			array( 'id' => 757, 'descripcion' => 'Monteros', 'id_provincia' => '25' ),
			array( 'id' => 758, 'descripcion' => 'Rio Chico', 'id_provincia' => '25' ),
			array( 'id' => 759, 'descripcion' => 'Simoca', 'id_provincia' => '25' ),
			array( 'id' => 760, 'descripcion' => 'Tafi Del Valle', 'id_provincia' => '25' ),
			array( 'id' => 761, 'descripcion' => 'Tafi Viejo', 'id_provincia' => '25' ),
			array( 'id' => 762, 'descripcion' => 'Trancas', 'id_provincia' => '25' ),
			array( 'id' => 763, 'descripcion' => 'Yerba Buena', 'id_provincia' => '25' ),
			array( 'id' => 536, 'descripcion' => 'Biedma', 'id_provincia' => '6' ),
			array( 'id' => 537, 'descripcion' => 'Cushamen', 'id_provincia' => '6' ),
			array( 'id' => 539, 'descripcion' => 'Escalante', 'id_provincia' => '6' ),
			array( 'id' => 540, 'descripcion' => 'Florentino Ameghino', 'id_provincia' => '6' ),
			array( 'id' => 541, 'descripcion' => 'Futaleufu', 'id_provincia' => '6' ),
			array( 'id' => 542, 'descripcion' => 'Gaiman', 'id_provincia' => '6' ),
			array( 'id' => 543, 'descripcion' => 'Gastre', 'id_provincia' => '6' ),
			array( 'id' => 545, 'descripcion' => 'Martires', 'id_provincia' => '6' ),
			array( 'id' => 546, 'descripcion' => 'Paso De Indios', 'id_provincia' => '6' ),
			array( 'id' => 547, 'descripcion' => 'Rawson', 'id_provincia' => '6' ),
			array( 'id' => 548, 'descripcion' => 'Rio Senguer', 'id_provincia' => '6' ),
			array( 'id' => 549, 'descripcion' => 'Sarmiento', 'id_provincia' => '6' ),
			array( 'id' => 550, 'descripcion' => 'Tehuelches', 'id_provincia' => '6' ),
			array( 'id' => 551, 'descripcion' => 'Telsen', 'id_provincia' => '6' ),
			array( 'id' => 204, 'descripcion' => 'Antartida', 'id_provincia' => '24' ),
			array( 'id' => 205, 'descripcion' => 'Malvinas', 'id_provincia' => '24' ),
			array( 'id' => 206, 'descripcion' => 'Rio Grande', 'id_provincia' => '24' ),
			array( 'id' => 207, 'descripcion' => 'Ushuaia', 'id_provincia' => '24' ),
			array( 'id' => 631, 'descripcion' => 'Bella Vista', 'id_provincia' => '8' ),
			array( 'id' => 632, 'descripcion' => 'Beron De Astrada', 'id_provincia' => '8' ),
			array( 'id' => 633, 'descripcion' => 'Capital', 'id_provincia' => '8' ),
			array( 'id' => 634, 'descripcion' => 'Concepcion', 'id_provincia' => '8' ),
			array( 'id' => 636, 'descripcion' => 'Curuzu Cuatia', 'id_provincia' => '8' ),
			array( 'id' => 637, 'descripcion' => 'Empedrado', 'id_provincia' => '8' ),
			array( 'id' => 638, 'descripcion' => 'Esquina', 'id_provincia' => '8' ),
			array( 'id' => 639, 'descripcion' => 'General Alvear', 'id_provincia' => '8' ),
			array( 'id' => 640, 'descripcion' => 'General Paz', 'id_provincia' => '8' ),
			array( 'id' => 641, 'descripcion' => 'Goya', 'id_provincia' => '8' ),
			array( 'id' => 642, 'descripcion' => 'Itati', 'id_provincia' => '8' ),
			array( 'id' => 643, 'descripcion' => 'Ituzaingo', 'id_provincia' => '8' ),
			array( 'id' => 644, 'descripcion' => 'Lavalle', 'id_provincia' => '8' ),
			array( 'id' => 645, 'descripcion' => 'Mburucuya', 'id_provincia' => '8' ),
			array( 'id' => 646, 'descripcion' => 'Mercedes', 'id_provincia' => '8' ),
			array( 'id' => 647, 'descripcion' => 'Monte Caseros', 'id_provincia' => '8' ),
			array( 'id' => 648, 'descripcion' => 'Paso De Los Libres', 'id_provincia' => '8' ),
			array( 'id' => 649, 'descripcion' => 'Saladas', 'id_provincia' => '8' ),
			array( 'id' => 650, 'descripcion' => 'San Cosme', 'id_provincia' => '8' ),
			array( 'id' => 651, 'descripcion' => 'San Luis Del Palmar', 'id_provincia' => '8' ),
			array( 'id' => 652, 'descripcion' => 'San Martin', 'id_provincia' => '8' ),
			array( 'id' => 653, 'descripcion' => 'San Miguel', 'id_provincia' => '8' ),
			array( 'id' => 654, 'descripcion' => 'San Roque', 'id_provincia' => '8' ),
			array( 'id' => 655, 'descripcion' => 'Santo Tome', 'id_provincia' => '8' ),
			array( 'id' => 656, 'descripcion' => 'Sauce', 'id_provincia' => '8' ),
			array( 'id' => 893, 'descripcion' => 'Calamuchita', 'id_provincia' => '7' ),
			array( 'id' => 894, 'descripcion' => 'Capital', 'id_provincia' => '7' ),
			array( 'id' => 895, 'descripcion' => 'Colon', 'id_provincia' => '7' ),
			array( 'id' => 896, 'descripcion' => 'Cruz Del Eje', 'id_provincia' => '7' ),
			array( 'id' => 897, 'descripcion' => 'General Roca', 'id_provincia' => '7' ),
			array( 'id' => 898, 'descripcion' => 'General San Martin', 'id_provincia' => '7' ),
			array( 'id' => 899, 'descripcion' => 'Ischilin', 'id_provincia' => '7' ),
			array( 'id' => 900, 'descripcion' => 'Juarez Celman', 'id_provincia' => '7' ),
			array( 'id' => 901, 'descripcion' => 'Marcos Juarez', 'id_provincia' => '7' ),
			array( 'id' => 902, 'descripcion' => 'Minas', 'id_provincia' => '7' ),
			array( 'id' => 903, 'descripcion' => 'Pocho', 'id_provincia' => '7' ),
			array( 'id' => 905, 'descripcion' => 'Punilla', 'id_provincia' => '7' ),
			array( 'id' => 906, 'descripcion' => 'Rio Cuarto', 'id_provincia' => '7' ),
			array( 'id' => 907, 'descripcion' => 'Rio Primero', 'id_provincia' => '7' ),
			array( 'id' => 908, 'descripcion' => 'Rio Seco', 'id_provincia' => '7' ),
			array( 'id' => 909, 'descripcion' => 'Rio Segundo', 'id_provincia' => '7' ),
			array( 'id' => 910, 'descripcion' => 'San Alberto', 'id_provincia' => '7' ),
			array( 'id' => 911, 'descripcion' => 'San Javier', 'id_provincia' => '7' ),
			array( 'id' => 912, 'descripcion' => 'San Justo', 'id_provincia' => '7' ),
			array( 'id' => 913, 'descripcion' => 'Santa Maria', 'id_provincia' => '7' ),
			array( 'id' => 914, 'descripcion' => 'Sobremonte', 'id_provincia' => '7' ),
			array( 'id' => 915, 'descripcion' => 'Tercero Arriba', 'id_provincia' => '7' ),
			array( 'id' => 916, 'descripcion' => 'Totoral', 'id_provincia' => '7' ),
			array( 'id' => 917, 'descripcion' => 'Tulumba', 'id_provincia' => '7' ),
			array( 'id' => 918, 'descripcion' => 'Union', 'id_provincia' => '7' ),
			array( 'id' => 764, 'descripcion' => 'Cochinoca', 'id_provincia' => '11' ),
			array( 'id' => 765, 'descripcion' => 'Dr Manuel Belgrano', 'id_provincia' => '11' ),
			array( 'id' => 766, 'descripcion' => 'El Carmen', 'id_provincia' => '11' ),
			array( 'id' => 767, 'descripcion' => 'Humahuaca', 'id_provincia' => '11' ),
			array( 'id' => 768, 'descripcion' => 'Ledesma', 'id_provincia' => '11' ),
			array( 'id' => 769, 'descripcion' => 'Palpala', 'id_provincia' => '11' ),
			array( 'id' => 770, 'descripcion' => 'Rinconada', 'id_provincia' => '11' ),
			array( 'id' => 772, 'descripcion' => 'San Antonio', 'id_provincia' => '11' ),
			array( 'id' => 773, 'descripcion' => 'San Pedro', 'id_provincia' => '11' ),
			array( 'id' => 774, 'descripcion' => 'Santa Barbara', 'id_provincia' => '11' ),
			array( 'id' => 775, 'descripcion' => 'Santa Catalina', 'id_provincia' => '11' ),
			array( 'id' => 776, 'descripcion' => 'Susques', 'id_provincia' => '11' ),
			array( 'id' => 777, 'descripcion' => 'Tilcara', 'id_provincia' => '11' ),
			array( 'id' => 778, 'descripcion' => 'Tumbaya', 'id_provincia' => '11' ),
			array( 'id' => 779, 'descripcion' => 'Valle Grande', 'id_provincia' => '11' ),
			array( 'id' => 780, 'descripcion' => 'Yavi', 'id_provincia' => '11' ),
			array( 'id' => 570, 'descripcion' => 'Corpen Aike', 'id_provincia' => '21' ),
			array( 'id' => 571, 'descripcion' => 'Deseado', 'id_provincia' => '21' ),
			array( 'id' => 572, 'descripcion' => 'Guer Aike', 'id_provincia' => '21' ),
			array( 'id' => 573, 'descripcion' => 'Lago Argentino', 'id_provincia' => '21' ),
			array( 'id' => 574, 'descripcion' => 'Lago Buenos Aires', 'id_provincia' => '21' ),
			array( 'id' => 575, 'descripcion' => 'Magallanes', 'id_provincia' => '21' ),
			array( 'id' => 576, 'descripcion' => 'Rio Chico', 'id_provincia' => '21' )
		);

		foreach ( $departamentos as $departamento ) {
			$entidadDepartamento = new Departamento();

			$entidadDepartamento->setDescripcion( $departamento['descripcion'] );
			$entidadDepartamento->setProvincia( $this->getReference( 'provincia' . $departamento['id_provincia'] ) );
			if ( isset( $departamento['codigo_departamento'] ) ) {
				$entidadDepartamento->setCodigo( $departamento['codigo_departamento'] );
			}


			$manager->persist( $entidadDepartamento );
			$this->addReference( 'departamento' . $departamento['id'], $entidadDepartamento );
		}


		$manager->flush();
	}

	public function getOrder() {
		// the order in which fixtures will be loaded
		// the lower the number, the sooner that this fixture is loaded
		return 3;
	}

}